 export default {
    invoiceNumber: "INV-2024-001",
    date: "January 15, 2024",
    dueDate: "February 14, 2024",
    company: {
      name: "Digital Solutions Inc.",
      street: "123 Business Street",
      city: "Toronto",
      province: "ON",
      postalCode: "M5V 3A8",
      country: "Canada",
      phone: "(416) 555-0123",
      email: "billing@digitalsolutions.com",
    },
    client: {
      name: "Acme Corporation",
      contact: "John Smith",
      street: "456 Client Avenue",
      city: "Vancouver",
      province: "BC",
      postalCode: "V6B 1A1",
      country: "Canada",
      email: "john.smith@acme.com",
    },
    projects: [
      {
        id: 1,
        name: "E-commerce Website Development",
        description: "Complete redesign and development of online store",
        tasks: [
          {
            id: 1,
            name: "UI/UX Design",
            description: "User interface and experience design",
            rate: 85,
            duration: 24,
            amount: 2040,
          },
          {
            id: 2,
            name: "Frontend Development",
            description: "React.js implementation",
            rate: 95,
            duration: 32,
            amount: 3040,
          },
          {
            id: 3,
            name: "Backend Integration",
            description: "API development and database setup",
            rate: 100,
            duration: 20,
            amount: 2000,
          },
        ],
      },
      {
        id: 2,
        name: "Mobile App Development",
        description: "iOS and Android application",
        tasks: [
          {
            id: 4,
            name: "App Design",
            description: "Mobile interface design",
            rate: 80,
            duration: 16,
            amount: 1280,
          },
          {
            id: 5,
            name: "React Native Development",
            description: "Cross-platform mobile development",
            rate: 90,
            duration: 28,
            amount: 2520,
          },
          {
            id: 6,
            name: "Testing & Deployment",
            description: "Quality assurance and app store deployment",
            rate: 75,
            duration: 12,
            amount: 900,
          },
        ],
      },
    ],
  }
